version: "3.9"
services:
  api:
    build: .
    image: realtime-chat-backend:dev
    command: npm run dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  mongo_data:
  redis_data: